package com.rulesengine;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Address implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "addressLine")
   private java.lang.String addressLine;
   @org.kie.api.definition.type.Label(value = "cityName")
   private java.lang.String cityName;
   @org.kie.api.definition.type.Label(value = "postalCode")
   private java.lang.String postalCode;
   @org.kie.api.definition.type.Label(value = "stateProv")
   private java.lang.String stateProv;
   @org.kie.api.definition.type.Label(value = "CountryName")
   public java.lang.String countryName;

   public Address()
   {
   }

   public java.lang.String getAddressLine()
   {
      return this.addressLine;
   }

   public void setAddressLine(java.lang.String addressLine)
   {
      this.addressLine = addressLine;
   }

   public java.lang.String getCityName()
   {
      return this.cityName;
   }

   public void setCityName(java.lang.String cityName)
   {
      this.cityName = cityName;
   }

   public java.lang.String getPostalCode()
   {
      return this.postalCode;
   }

   public void setPostalCode(java.lang.String postalCode)
   {
      this.postalCode = postalCode;
   }

   public java.lang.String getStateProv()
   {
      return this.stateProv;
   }

   public void setStateProv(java.lang.String stateProv)
   {
      this.stateProv = stateProv;
   }

   public java.lang.String getCountryName()
   {
      return this.countryName;
   }

   public void setCountryName(java.lang.String countryName)
   {
      this.countryName = countryName;
   }

   public Address(java.lang.String addressLine, java.lang.String cityName,
         java.lang.String postalCode, java.lang.String stateProv,
         java.lang.String countryName)
   {
      this.addressLine = addressLine;
      this.cityName = cityName;
      this.postalCode = postalCode;
      this.stateProv = stateProv;
      this.countryName = countryName;
   }

}