package com.rulesengine;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class AuditTrail implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("rule")
   private java.lang.String rule;
   @org.kie.api.definition.type.Label("action")
   private java.lang.String action;
   @org.kie.api.definition.type.Label("score")
   private int score;

   private java.lang.String notes;

   @org.kie.api.definition.type.Label(value = "version")
   private java.lang.String version;

   public AuditTrail()
   {
   }

   public java.lang.String getRule()
   {
      return this.rule;
   }

   public void setRule(java.lang.String rule)
   {
      this.rule = rule;
   }

   public java.lang.String getAction()
   {
      return this.action;
   }

   public void setAction(java.lang.String action)
   {
      this.action = action;
   }

   public int getScore()
   {
      return this.score;
   }

   public void setScore(int score)
   {
      this.score = score;
   }

   public java.lang.String getNotes()
   {
      return this.notes;
   }

   public void setNotes(java.lang.String notes)
   {
      this.notes = notes;
   }

   public java.lang.String getVersion()
   {
      return this.version;
   }

   public void setVersion(java.lang.String version)
   {
      this.version = version;
   }

   public AuditTrail(java.lang.String rule, java.lang.String action, int score,
         java.lang.String notes, java.lang.String version)
   {
      this.rule = rule;
      this.action = action;
      this.score = score;
      this.notes = notes;
      this.version = version;
   }

}