package com.rulesengine;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Billing implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("address")
   private com.rulesengine.Address address;
   @org.kie.api.definition.type.Label("dollarAmount")
   private java.lang.Integer dollarAmount;
   @org.kie.api.definition.type.Label("person")
   private com.rulesengine.PersonName person;

   @org.kie.api.definition.type.Label(value = "email")
   private java.lang.String email;

   public Billing()
   {
   }

   public com.rulesengine.Address getAddress()
   {
      if (null == this.address)
      {
         Address add = new Address();
         this.address = add;
      }
      return this.address;
   }

   public void setAddress(com.rulesengine.Address address)
   {
      this.address = address;
   }

   public java.lang.Integer getDollarAmount()
   {
      return this.dollarAmount;
   }

   public void setDollarAmount(java.lang.Integer dollarAmount)
   {
      this.dollarAmount = dollarAmount;
   }

   public com.rulesengine.PersonName getPerson()
   {
      return this.person;
   }

   public void setPerson(com.rulesengine.PersonName person)
   {
      this.person = person;
   }

   public java.lang.String getEmail()
   {
      return this.email;
   }

   public void setEmail(java.lang.String email)
   {
      this.email = email;
   }

   public Billing(com.rulesengine.Address address, java.lang.Integer dollarAmount,
         com.rulesengine.PersonName person, java.lang.String email)
   {
      this.address = address;
      this.dollarAmount = dollarAmount;
      this.person = person;
      this.email = email;
   }

}