package com.rulesengine;

import java.util.List;
import java.util.ArrayList;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class OrderRequest implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("billingCountry")
   private java.lang.String billingCountry;
   @org.kie.api.definition.type.Label("IPCountry")
   private java.lang.String IPCountry;
   @org.kie.api.definition.type.Label("CCCountry")
   private java.lang.String CCCountry;
   @org.kie.api.definition.type.Label("DollarAmount")
   private java.lang.Integer dollarAmount;
   @org.kie.api.definition.type.Label("billingName")
   private java.lang.String billingName;
   @org.kie.api.definition.type.Label("action")
   private java.lang.String action;
   @org.kie.api.definition.type.Label("notes")
   private java.lang.String notes;

   @org.kie.api.definition.type.Label("audit")
   private java.util.List<com.rulesengine.AuditTrail> audit;

   @org.kie.api.definition.type.Label("productName")
   private java.lang.String productName;

   @org.kie.api.definition.type.Label("emailTotalApproves")
   private Integer emailTotalApproves;

   @org.kie.api.definition.type.Label("ShippingMethod")
   private java.lang.String shippingMethod;

   @org.kie.api.definition.type.Label("email")
   private java.lang.String email;

   @org.kie.api.definition.type.Label("billingSurName")
   private java.lang.String billingSurName;

   @org.kie.api.definition.type.Label("totalAuditScore")
   private int totalAuditScore;

   @org.kie.api.definition.type.Label(value = "billing")
   private com.rulesengine.Billing billing;

   public OrderRequest()
   {
   }

   public java.lang.String getBillingCountry()
   {
      return this.billingCountry;
   }

   public void setBillingCountry(java.lang.String billingCountry)
   {
      this.billingCountry = billingCountry;
   }

   public java.lang.String getIPCountry()
   {
      return this.IPCountry;
   }

   public void setIPCountry(java.lang.String IPCountry)
   {
      this.IPCountry = IPCountry;
   }

   public java.lang.String getCCCountry()
   {
      return this.CCCountry;
   }

   public void setCCCountry(java.lang.String CCCountry)
   {
      this.CCCountry = CCCountry;
   }

   public java.lang.Integer getDollarAmount()
   {
      return this.dollarAmount;
   }

   public void setDollarAmount(java.lang.Integer dollarAmount)
   {
      this.dollarAmount = dollarAmount;
   }

   public java.lang.String getBillingName()
   {
      return this.billingName;
   }

   public void setBillingName(java.lang.String billingName)
   {
      this.billingName = billingName;
   }

   public java.lang.String getAction()
   {
      return this.action;
   }

   public void setAction(java.lang.String action)
   {
      this.action = action;
   }

   public java.lang.String getNotes()
   {
      return this.notes;
   }

   public void setNotes(java.lang.String notes)
   {
      this.notes = notes;
   }

   public java.util.List<com.rulesengine.AuditTrail> getAudit()
   {
      if (null == this.audit)
      {
         List<AuditTrail> trail = new ArrayList<AuditTrail>();
         this.audit = trail;
      }

      return this.audit;
   }

   public void setAudit(java.util.List<com.rulesengine.AuditTrail> audit)
   {
      this.audit = audit;
   }

   public java.lang.String getProductName()
   {
      return this.productName;
   }

   public void setProductName(java.lang.String productName)
   {
      this.productName = productName;
   }

   public java.lang.String getShippingMethod()
   {
      return this.shippingMethod;
   }

   public void setShippingMethod(java.lang.String shippingMethod)
   {
      this.shippingMethod = shippingMethod;
   }

   public java.lang.Integer getEmailTotalApproves()
   {
      return this.emailTotalApproves;
   }

   public void setEmailTotalApproves(java.lang.Integer emailTotalApproves)
   {
      this.emailTotalApproves = emailTotalApproves;
   }

   public java.lang.String getEmail()
   {
      return this.email;
   }

   public void setEmail(java.lang.String email)
   {
      this.email = email;
   }

   public java.lang.String getBillingSurName()
   {
      return this.billingSurName;
   }

   public void setBillingSurName(java.lang.String billingSurName)
   {
      this.billingSurName = billingSurName;
   }

   public int getTotalAuditScore()
   {
      int totalscore = 0;
      if (null != getAudit())
      {
         for (AuditTrail aTrail : getAudit())
         {
            totalscore += aTrail.getScore();
         }
      }
      this.totalAuditScore = totalscore;
      return this.totalAuditScore;
   }

   public void setTotalAuditScore(int totalAuditScore)
   {
      this.totalAuditScore = totalAuditScore;
   }

   public com.rulesengine.Billing getBilling()
   {
       if (null == this.billing)
      {
         Billing bill = new Billing();
         this.billing = bill;
      }
      return this.billing;
   }

   public void setBilling(com.rulesengine.Billing billing)
   {
       
      this.billing = billing;
   }

   public OrderRequest(java.lang.String billingCountry,
         java.lang.String IPCountry, java.lang.String CCCountry,
         java.lang.Integer dollarAmount, java.lang.String billingName,
         java.lang.String action, java.lang.String notes,
         java.util.List<com.rulesengine.AuditTrail> audit,
         java.lang.String productName, java.lang.Integer emailTotalApproves,
         java.lang.String shippingMethod, java.lang.String email,
         java.lang.String billingSurName, int totalAuditScore,
         com.rulesengine.Billing billing)
   {
      this.billingCountry = billingCountry;
      this.IPCountry = IPCountry;
      this.CCCountry = CCCountry;
      this.dollarAmount = dollarAmount;
      this.billingName = billingName;
      this.action = action;
      this.notes = notes;
      this.audit = audit;
      this.productName = productName;
      this.emailTotalApproves = emailTotalApproves;
      this.shippingMethod = shippingMethod;
      this.email = email;
      this.billingSurName = billingSurName;
      this.totalAuditScore = totalAuditScore;
      this.billing = billing;
   }

}