package com.rulesengine;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class PersonName implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "givenName")
   private java.lang.String givenName;
   @org.kie.api.definition.type.Label(value = "surname")
   private java.lang.String surname;

   public PersonName()
   {
   }

   public java.lang.String getGivenName()
   {
      return this.givenName;
   }

   public void setGivenName(java.lang.String givenName)
   {
      this.givenName = givenName;
   }

   public java.lang.String getSurname()
   {
      return this.surname;
   }

   public void setSurname(java.lang.String surname)
   {
      this.surname = surname;
   }

   public PersonName(java.lang.String givenName, java.lang.String surname)
   {
      this.givenName = givenName;
      this.surname = surname;
   }

}